name: 'Get Last Version'
description: 'Get the latest stable version of a GitHub project or other software'
inputs:
  action:
    description: 'The action to perform (e.g., get)'
    required: false
    default: 'get'
  repository:
    description: 'Repository URL or software name'
    required: false
  branch:
    description: 'Branch name (optional)'
    required: false
  format:
    description: 'The output format of the result (version, json, or assets)'
    required: false
    default: 'version'
  extra_args:
    description: 'Extra args'
    required: false
  github_token:
    description: 'GitHub token (optional)'
    required: false
  working_directory:
    description: 'The working directory for the action'
    required: false
    default: './'
outputs:
  last_version:
    description: 'The latest stable version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--action"
    - ${{ inputs.action }}
    - "--format"
    - ${{ inputs.format }}
    - "--repository"
    - ${{ inputs.repository }}
    - "--branch"
    - ${{ inputs.branch }}
    - "--github_token"
    - ${{ inputs.github_token }}
    - "--extra_args"
    - ${{ inputs.extra_args }}
    - "--working_directory"
    - ${{ inputs.working_directory }}
branding:
  icon: 'arrow-down'
  color: 'purple'
